### ISSUE TITLE
Can't setup administrator's password

### ISSUE THREAD

**Issue by fernnguyen** [medic/medic-os#14]
Hi, 
I used ISO file at: http://dev.medicmobile.org/downloads/medic-os/latest/medic-os-v1.1.0-20170410-x64-virtual.iso

But, when i seting up the password, it's said: System password setup failed: problem with server.

**Comment by alxndrsn** [comment]
The screenshot linked is:

![cfde7299f0e945fdb57f2c8d15aaaa73](https://cloud.githubusercontent.com/assets/191496/25371581/c0ab07d4-2991-11e7-984a-d858102626d2.png)

(username, email, full name redacted)

**Comment by garethbowen** [comment]
I think @ngaruko might've come across this issue too.

**Comment by fernnguyen** [comment]
Hello, any body here? :'(

**Comment by garethbowen** [comment]
@browndav Any ideas on this one?

**Comment by ghost** [comment]
This is a known issue and we have a couple people working on it now. We'll be doing a Medic OS release within the next month and this is (obviously) on the must-fix list. We're also making some changes to how we do bootstrapping, first-run setup, and app deployment (horticulturalist), which have had knock-on effects here. Sorry for the delay. Will update ASAP.

**Comment by ghost** [comment]
This issue has been superseded by a completely new automatic bootstrap process and conversion over to Docker. Closing.
