### ISSUE TITLE
Redundant options in `adduser` call

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-os#17]
At https://github.com/medic/medic-os/blob/master/platform/packages/medic-rdbms/scripts/medic-rdbms/install#L89-L90, `adduser` is called with both `-H` and `-h` flags.  These appear to be contradictory.

**Comment by ghost** [comment]
This is now in [the initrd boot/include/utility](https://github.com/medic/medic-os/blob/dev/platform/initrd/common/boot/include/utility#L96) file, and has been refactored.

The Busybox version of `adduser` is a little weird (e.g. `-H -h /var/empty` means "set $HOME to /var/empty but don't create it`), but all of this should be skipped now in the Dockerized Ubuntu-based builds. Closing; the Busybox code shouldn't be hit in production in 3.0+, and then we'll remove it.
