### ISSUE TITLE
Create credential import script

### ISSUE THREAD

**Issue by ghost** [medic/medic-os#2]
We need a script that does the following:
1. Downloads a set of OpenSSH public keys over an bidirectionally-authenticated encrypted connection, and replaces `~/.ssh/authorized_keys` with a file that permits access to only the holders of those keys. The best current suggestion is to use a Git repository for this, as it keeps a record of all modifications and `git` is easily scriptable.
2.  Generates a random password, sets the CouchDB `admin` and local `root` password to that random password, then prints the same random password to standard output.

We're planning to use this as part of a broader credential management strategy, which will include a password management tool that consumes the random password generated in (2) above. This script will probably be run over SSH from a central location initially, but may be scheduled via `cron` locally at some later date.

**Comment by ghost** [comment]
Eventual target for the randomly-generated password in step two, above: https://github.com/medic/medic-projects/issues/466.

**Comment by ghost** [comment]
Progress over in https://gist.github.com/browndav/0dadee2067a6e3ecf75a8e2f7604b5ec. This works and allows you to be selective (e.g. `authorize-ssh-keys https://github.com/medic/medic-credentials ~/.ssh/id_bootstrap ~/.ssh/authorized_keys '*@medicmobile.org'`) but doesn't yet handle removal or replacement. Figure out if we should handle either of those cases then finish this up.

**Comment by ghost** [comment]
@SCdF: Any strong opinions on whether or not we should try to handle manual additions to `authorized_keys`? I'm inclined to just blow the file away every time and require that all keys be managed through `git` commit/push operations. End of the day for me, though, so I figured I'd ask for your overnight opinion.

**Comment by SCdF** [comment]
@browndav agree. Makes things simpler, clearer, and reduces the chance of getting into funky states

**Comment by ghost** [comment]
This issue has been superseded by the SSH certificate work in medic/medic-credentials. SSH certificates allow us to authorize a root certificate authority once, and then manage authorization and revocation centrally _without touching each individual instance_. Closing.
