### ISSUE TITLE
enable default compaction in couchdb conf

### ISSUE THREAD

**Issue by mandric** [medic/medic-os#25]
example taken from default.ini:

```
[compactions]
_default = [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}, {from, "23:00"}, {to, "04:00"}]
```

see http://docs.couchdb.org/en/latest/config/compaction.html#compaction-daemon-rules

**Comment by browndav** [comment]
In https://github.com/medic/medic-os/blob/dev/platform/packages/medic-core/settings/medic-core/couchdb/default.ini, closing.
