### ISSUE TITLE
Nginx: Don't log proxied connection failover

### ISSUE THREAD

**Issue by ghost** [medic/medic-os#3]
In https://github.com/medic/medic-webapp/issues/2476, we saw `nginx` logging entries like this to `/srv/storage/medic-core/nginx/logs/error-ssl.log`:

`2016/07/11 01:09:43 [error] 19985#0: *5901 connect() failed (111: Connection refused) while connecting to upstream, client: 111.69.85.204, server: _, request: "GET /medic/ HTTP/1.1", upstream: "http://127.0.0.1:280/medic/", host: "lg.app.medicmobile.org", referrer: "https://lg.app.medicmobile.org/medic/_design/medic/_rewrite/"`

This doesn't impact normal operation – we _want_ the connection to fail over – but it does spam the log and waste peoples' time when they're looking for real problems. Find out how to get rid of this, either by explicitly preventing logging in that situation, or by finding a way to reasonably cache the failure and generally not log every failing-over request.

**Comment by mandric** [comment]
I wonder if there's a way we can avoid the failover all together.  Wondering if there is a way that nginx can check if concierge is running by looking for a file or something (e.g. /var/run/concierge.pid) and then have an override in the config on / when that condition is met.

**Comment by ghost** [comment]
Yeah, it'd be possible to use something like config templating (N.B. there's a currently-unused implementation of that shipping with the OS images) and a special shutdown procedure that changes a variable and rewrites nginx.conf.

**Comment by ghost** [comment]
This issue will be eliminated by the removal of concierge and the addition of horticulturalist.

**Comment by ghost** [comment]
Removal/replacement has resolved this issue. Closing.
