### ISSUE TITLE
`svc-up` does not return error when asked to start a non-existent package

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-os#39]
# Environment

1.1.0-20150520-x64-virtual

# Observed behaviour

```
$ sudo svc-up nonsense; echo $?
Success: Finished starting services in package 'nonsense'
0
```

# Expected behaviour

Trying to start a service which doesn't exist should give an error, and return non-zero status code.

**Comment by browndav** [comment]
Confirmed; this seems to affect all of the `svc-*` utilities when they're used in "whole package" mode, i.e. trying to start/stop/restart/reload all of the services provided by the package `nonsense`. Fix on the way.

**Comment by browndav** [comment]
I have a fix in my local tree; I'll test again tomorrow morning and then push the changeset.

**Comment by browndav** [comment]
Pushed. Building new images for acceptance testing now.

**Comment by browndav** [comment]
http://dev.medicmobile.org/downloads/medic-os/20150623/

**Comment by alxndrsn** [comment]
LGTM.  Let me know which commit this was done on, and I'll review the code too if you want.

**Comment by browndav** [comment]
Thanks. Should be the June 16th commit from https://github.com/medic/medic-os/commits/dev. The fix is right at the top of https://github.com/browndav/medic-os/commit/08604c36f63e6b9ace568096a333f2f455e3cb4e; everything else (including the commits pushed on the 23rd) was cleanup/hardening.

**Comment by alxndrsn** [comment]
Did `supervisor_service_exists` and `supervisor_package_exists` already exist?
What's with the different handling of exit-on-fail?  E.g. https://github.com/medic/medic-os/blob/08604c36f63e6b9ace568096a333f2f455e3cb4e/platform/initrd/common/boot/supervisor-disable#L51 exits immediately, whereas https://github.com/medic/medic-os/blob/08604c36f63e6b9ace568096a333f2f455e3cb4e/platform/initrd/common/boot/supervisor-disable#L57 stores status codes in `rv`, and appears to have a bug in that it will only exit if disabling the *final* package fails.  I assume the intention was to try disabling *everything* in the list, but exit non-zero if *any* of these fails.

And subjectively, you might consider changing:

    disable "$package" "$service" 't'
    local r="$?"; [ "$r" -eq 0 ] || exit "$r"

to

    disable "$package" "$service" 't' || exit $?

**Comment by browndav** [comment]
The `exit` should just escape the `while` subshell and not the whole script, if I'm reading it right. You're right about the final part IIRC; `||` preserves the exit status as is (e.g. doesn't reduce something like `127` down to `1`) so it'd be safe.
