### ISSUE TITLE
git submodule fails because perl is missing

### ISSUE THREAD

**Issue by mandric** [medic/medic-os#46]
```
$ git submodule init api
/srv/software/medic-core/v1.6.1/x64/libexec/git-core/git-submodule: line 1: /usr/bin/perl: not found
```
If we update git and compile with NO_PERL that might be a fix.  https://www.mail-archive.com/git@vger.kernel.org/msg77144.html

**Comment by browndav** [comment]
According to your link, `NO_PERL` just aliases git-submodule to unimplemented.sh, which provides no additional functionality and seems to produce a marginally-less-informational error message. What's the goal here? In general, Perl is too large to stay under the 100MiB design limit until Lucene and the JVM are purged, and even then the cost/benefit doesn't seem worth it here (absent other uses for it).

**Comment by mandric** [comment]
Yeah it doesn't seem worth it, closing for now.  Workaround is to just checkout the modules with git clone.

**Comment by browndav** [comment]
Closing.
