### ISSUE TITLE
Cannot download JRE archive

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-os#8]
On Ubuntu 16.04.1, after running `sudo platform/config/debian/scripts/prepare-system`:

```
$ file='medic-os-java-x64-latest.tar.xz' &&
> curl -LO# "https://medic-mobile.s3.amazonaws.com/medic-os/build/source/$file" &&
> tar -xvJf "$file"
######################################################################## 100.0%
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by alxndrsn** [comment]
Just checked the content of `medic-os-java-x64-latest.tar.xz`:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>...
```

Updating the bug title!

**Comment by ghost** [comment]
Looks like AWS permissions; let me take a look today. Actually, no, that should be pulling from the `medic` bucket, which is altogether different from `medic-mobile`.

**Comment by ghost** [comment]
Arg, documentation bug, I see it now. Not related to the build. Will fix now in https://github.com/medic/medic-os/blob/master/README.md. The automated AWS builds do this via a script in the source tree, which may have been why I was getting confused.
